# This is a basic workflow to help you get started with Actions

name: deploy-client

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
    paths:
      - "client/**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: cd client && docker build -t sumitgovilstudy/client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        # Values are fetched from secrets
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push sumitgovilstudy/client
      - uses: digitalocean/action-doctl@v2 # Install Doctl into running Github container
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing # Switch to doctl context
      - run: kubectl rollout restart deployment client-depl # Restart deployment
